before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/spotlightd/main.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

nfpms:
  - vendor: Kunal Saini
    homepage: https://github.com/kunal-saini/spotlight-manager
    maintainer: Kunal Saini <kunalsaini.exe@gmail.com>
    description: Ubuntu Spotlight Wallpaper Manager
    license: MIT
    formats:
      - deb
    contents:
      - src: packaging/systemd/spotlightd.service
        dst: /lib/systemd/system/spotlightd.service
      - src: ./logo.png
        dst: /usr/share/spotlight-manager/logo.png
    scripts:
      postinstall: packaging/scripts/postinstall.sh
      preremove: packaging/scripts/preremove.sh

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"